# Generated by Django 3.2.9 on 2021-11-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20211110_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpets',
            name='photos',
            field=models.ImageField(upload_to='images\\%d\\%m\\%Y'),
        ),
    ]
