# Generated by Django 3.2.9 on 2021-11-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_allpets_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allpets',
            name='photos',
        ),
        migrations.AddField(
            model_name='allpets',
            name='age',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='allpets',
            name='type',
            field=models.CharField(default='dog', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allpets',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
