# Generated by Django 3.2.9 on 2021-11-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_allpets_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpets',
            name='photos',
            field=models.ImageField(default='', upload_to='images_751b6415-47a8-4447-a379-20c6eab2ceab'),
        ),
    ]
