# Generated by Django 3.2.9 on 2021-11-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_alter_allpets_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpets',
            name='photos',
            field=models.ImageField(default='', upload_to='images_15f3f094-4b7b-42ef-b78d-813c47635229'),
        ),
    ]
