# Generated by Django 3.2.9 on 2021-11-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_alter_allpets_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpets',
            name='photos',
            field=models.ImageField(null=True, upload_to='images_9cb6b8a5-ff3c-4793-a663-ee6740e55dac'),
        ),
    ]
