# Generated by Django 3.2.9 on 2021-11-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_auto_20211110_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpets',
            name='photos',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
