# Generated by Django 3.2.9 on 2021-11-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0012_alter_allpets_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allpets',
            name='photos',
        ),
        migrations.AlterField(
            model_name='petphoto',
            name='photos',
            field=models.ImageField(upload_to='images/%Y-%m-%d/'),
        ),
    ]
